*Meng Lu*
### Overall Grade: 103/110

### Quality of report: 10/10

-   Is the homework submitted (git tag time) before deadline (Due Sep 25, 2019 @ 11:59PM)?

    Yes. `2019-09-25 20:58:38`. 

-   Is the final report in a human readable format html? 

    Yes. `html`.

-   Is the report prepared as a dynamic document (R markdown) for better reproducibility?

    Yes. `Rmd`.

-   Is the report clear (whole sentences, typos, grammar)? Do readers have a clear idea what's going on and how are results produced by just reading the report? 

	  Yes. 
	  
### Correctness and efficiency of solution: 58/60

-   Q1 (10/10)

-   Q2 (18/20)
	 (-2 pt), For founder we should leave it blank, instead of putting `0` - otherwise the program will look for father/mother with ID, `0`.   

-   Q3 (30/30) consider round the report 
  
    
### Usage of Git: 6/10

-   Are branches (`master` and `develop`) correctly set up? Is the hw submission put into the `master` branch?

    Couldn't find branch merge, etc. info.  (-2pts)

-   Are there enough commits? Are commit messages clear?  

    Not really. There are only a couple commits and message not very informative. (-1pt)  
   
-   Is the hw1 submission tagged? 

    Yes. 

-   Are the folders (`hw1`, `hw2`, ...) created correctly? 

    Yes.
  
-   Do not put a lot auxiliary files into version control. 

	  There is a blank file `out.fam` in the folder. (-1pt)


### Reproducibility: 9/10

-   Are the materials (files and instructions) submitted to the `master` branch sufficient for reproducing all the results? Just click the `knit` button will produce the final `html` on teaching server? 

  	No. I need to install package `"pacman"` (-1pt)
  	

-   If necessary, are there clear instructions, either in report or in a separate file, how to reproduce the results?

    Yes.

### R code style: 20/20
-   [Rule 3.](https://google.github.io/styleguide/Rguide.xml#linelength) The maximum line length is 80 characters. 


-   [Rule 4.](https://google.github.io/styleguide/Rguide.xml#indentation) When indenting your code, use two spaces.

-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.). 


-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Do not place a space before a comma, but always place one after a comma. 

	Violation:
	
	Most of your code complaned style. There are few placed your didn't: 
	
-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Place spaces around all binary operators (=, +, -, &lt;-, etc.). 


-   [Rule 5.](https://google.github.io/styleguide/Rguide.xml#spacing) Do not place a space before a comma, but always place one after a comma. 





